### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by dm82m** [sknull/googlecontactsconverter#3]
> {9:35}~/Downloads ➭ java -jar googlecontactsconverter.jar "Google-temp" "contacts.csv" "contacts"
> Exception in thread "main" java.lang.IllegalStateException: Could not marshall phonebook
> 	at de.visualdigits.fritzbox.model.phonebook.Phonebooks.marshal(Phonebooks.java:125)
> 	at de.visualdigits.transformer.GoogleContacts2FritzboxTransformer.transform(GoogleContacts2FritzboxTransformer.java:67)
> 	at de.visualdigits.transformer.GoogleContacts2FritzboxTransformer.transform(GoogleContacts2FritzboxTransformer.java:31)
> 	at de.visualdigits.GoogleContactsConverter.main(GoogleContactsConverter.java:37)
> Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
>  - with linked exception:
> [java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
> 	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:232)
> 	at javax.xml.bind.ContextFinder.find(ContextFinder.java:375)
> 	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
> 	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
> 	at de.visualdigits.fritzbox.model.phonebook.Phonebooks.marshal(Phonebooks.java:114)
> 	... 3 more
> Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:92)
> 	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:125)
> 	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:230)
> 	... 7 more

`{9:40}~/Downloads ➭ java --version
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)`

**Comment by sknull** [comment]
Hallo,

das liegt daran das ich das Programm noch mit Java 8 compiliert habe. Mit einer JRE 1.8 wird es funktionieren.
Werde ich fleich fixen.

Gruß,
Stephan

**Comment by sknull** [comment]
So es gibt ein neues release das ich mit jdk 13 compiliert habe. Sollte jetzt gehen.

**Comment by dm82m** [comment]
hat 1a funktioniert, danke dir!
